### PR TITLE
feat: ssr of images

### PR DESCRIPTION
**Pull request by ipeglin**
## Changes
* Truncating `webpage` attribute in `/admin/companies` to fit table into viewport.
* Changing table header for registration code to fit table into viewport.

### CODE REVIEW

**Comment by AasmundN** [comment]
# Changes
- Updated images to use Nuxt-Image. Didn't turn out super elegant, but it seems to work fine for the most part. The home banner really needs some work in a separate PR.

**Review by ipeglin — COMMENTED** [review]
Everything is looking very nice! Don't fully understand why the previous styling resulted in overlapping divs on Safari, but everything seems to be working now! 

Where there anything spesific you thought of when it comes to refactoring the companyHero component?

**Comment by AasmundN** [comment]
Just that the image needs to be updated and maybe scaled a bit.

**Review by ranerhei — APPROVED** [review]
looks good

**Pull request merged**
