### PR TITLE
refactor: access levels and user types

### PR DESCRIPTION
**Pull request by AasmundN**
# Changes
- Change implementation of access levels and user types as described in issue #85.
- Move global state `registeringUser` from _appStore_ to _authStore_.

### CODE REVIEW

**Review by JStoresund — COMMENTED** [review]
All the code looks logical. 

Upon testing the site with different userTypes, the routes did work as intended, with the admin sites only being available if the userType was set to "admin". For any other userType, the site redirects to the userpage. 

I personally don't know too much about cybersecurity, so I would like for at least one more person to take a look, just in case I missed something.

The only criticism I would add is it's difficult to find what accessType each route has. An easily readable way could be to have a metadata for each page that tells who will be able to access them. For instance: 

```
definePageMeta({
   accessType: ["admin", "company"],
})
```

for a company page.

This might create a security hazard, considering this data will be available on the client side.

**Comment by AasmundN** [comment]
@JStoresund all the routes in the admin folder are subroutes of `/admin`. The way route meta data works is that routes inherit the meta data of their parent routes. So if you look in the `admin.vue` file you will indeed see the meta data defined there.

**Review by ipeglin — CHANGES_REQUESTED** [review]
Functionality-wise everything seems to be working as intended. However, I would like to see some explicit TS types for different values such as the different access levels, and user types.

**Review by ipeglin — APPROVED** [review]
LGTM

**Pull request merged**
